name: Deployment
on:
  issues:
    types:
      - opened
  #workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'content-type: application/json' \
            -d '{"labels": ["bug"]}' 

curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/issues/ISSUE_NUMBER/labels \
  -d '{"labels":["bug","enhancement"]}'


  #deploy:
  #  needs: build
  #  uses: ./.github/workflows/reusable.yaml
  #    with:
  #      artifact-name: files
