name: Deployment
on:
  workflow-dispatch:
  #push:
  #  branches:
  #    - main
  #    - dev
jobs:
  job1:
    environment: testing
    #strategy:
      #matrix:
      #  node-version: [ 16, 18 ]
      #  os: [ ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ubuntu-latest  # ubuntu-latest
    steps:
      - name: Deploy
        uses: ./workflows/reuse.yaml
        with:
          art: ${{ matrix.node-version }}
