name: Deployment
on:
  issues:
    types:
      - opened
  #workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
            --url https://api.github.com/repos/psolomon-services/udemy-gha2/issues/${{ github.event.issue.number }}/labels \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'Content-type: application/json' \
            -d '{"labels": ["bug"]}'
  #deploy:
  #  needs: build
  #  uses: ./.github/workflows/reusable.yaml
  #    with:
  #      artifact-name: files
