name: Deployment
on:
  push:
    branches:
      - main
      - dev
jobs:
  job1:
    environment: testing
    env:
      MY_SECRET_KEY:  ${{ secrets.MY_SECRET_KEY }}
      MY_ENV: ${{ env.MY_ENV }}
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: echo1
        id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - name: echo2
        id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - name: echo my env
        run: echo $MY_ENV
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

  
