name: Deployment
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #    - dev
jobs:
  job1:
    environment: testing
    #strategy:
      #matrix:
      #  node-version: [ 16, 18 ]
      #  os: [ ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ubuntu-latest  # ubuntu-latest
    steps:
      - name: save temp artifact
        run: "mkdir tmp; echo 'hello world' > tmp/hello.txt"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: tmp
      - name: Deploy
        uses: ./.github/workflows/reusable.yml
        with:
          artifact-name: tmp
