name: Deployment
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #    - dev
jobs:
  build:
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: ls code
        run: ls -alR
      - name: save temp artifact
        run: "mkdir ./tmp; echo 'hello world' > tmp/hello.txt"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: ./tmp

  deploy:
    needs: build
    environment: testing
    runs-on: ubuntu-latest  # ubuntu-latest
    uses: ./.github/workflows/reusable.yaml
      with:
        artifact-name: files
