name: Reusable Deploy
on:
  workflow_call:
    inputs:
      files:
        description: files to get
        required: false
        default: myfiles
        type: string
    #secrets:
    #  my-secret:
    #  required: true    
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/download-artifact@v3
          with:
            name: ${{ inputs.files }}
        - name: List files
          run: ls
        
