name: Reusable Deploy
on:
  workflow_call:
    inputs:  greeting:
      description: Greeting text
      required: false
      default: hello
      type: string
    secrets:
      my-secret:
      required: true
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/download-artifact@v3
          with:
            name: ${{ inputs.artifact-name }}
        - name: List files
          run: ls
